# Generated by Django 4.2.2 on 2023-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogapp',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AlterField(
            model_name='blogapp',
            name='media',
            field=models.ImageField(upload_to='blog/', verbose_name='Медиа'),
        ),
    ]
