# Generated by Django 4.2.2 on 2023-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тест'},
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
